services:
  web:
    image: support_forum
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: